### ISSUE TITLE
Text columns are categorized as categorical columns

### ISSUE THREAD

**Issue by PaulZGit** [hpi-bp1819-naumann/shift-detector#115]
At least this appears to be the case in the current master with the pokemon dataset
<img width="827" alt="Screen Shot 2019-06-21 at 10 55 23" src="https://user-images.githubusercontent.com/24995121/59910926-2e161780-9413-11e9-8c2e-863b68740f37.png">

**Comment by PaulZGit** [comment]
Okay, problems seems to  be more. Lots of numerical cols are seen as numerical too. 

See 'Name', 'Speed', '#', 'Attack', 'HP' all in categorical

**Comment by janwestphal306** [comment]
Recognized the same. Fixed by #117
