### ISSUE TITLE
Remove the 'restore_best_weights' parameter in Word_Prediction_Precalculation

### ISSUE THREAD

**Issue by malte-b** [hpi-bp1819-naumann/shift-detector#138]
The parameter 'restore_best_weights' was only recently added in Keras 2.2.3. To ensure backwards compatibility, we should remove this parameter.

**Comment by mschroederi** [comment]
I think we should instead require Keras with a version >=2.2.3

**Comment by malte-b** [comment]
This would be bad, because then we would not support python 3.4 and Eider in particular

**Comment by malte-b** [comment]
Actually nevermind, I tried to update Keras manually on python 3.4 and now it works with 2.2.4.
