### ISSUE TITLE
Style Improvements for DQMetricsCheck

### ISSUE THREAD

**Issue by PaulZGit** [hpi-bp1819-naumann/shift-detector#144]
- Tabelle mit Head DS1, DS2, Threshold und Diff (besser Diff und threshold tauschen!)
    - Absolute Werte mit anzeigen
    - Darstellen, wie das diff berechnet wird, in welche Richtung der Threshold geht
    - +/- bei allen thresholds anzeigen

- Spalten immer alphabetisch sortieren (auch Plots)

- Bezeichnungen vereinheitlichen, Utils-Funktion; Beschriftung an Datasets anpassen (Datenset1, 2)
- Labels für Boxplots einheitlich machen

**Comment by malte-b** [comment]
Could you please handle NaN values in numerical columns too? Currently the visualizations break because of them
